### ISSUE TITLE
cant install it in my ros kinetic

### ISSUE THREAD

**Issue by sezan92** [oKermorgant/cdpr#1]

**Comment by yang2lalang** [comment]
could you be more explicit about the problem you are having

please post any error screen shots or messages you have

what are the steps you followed for the installation

did you create a catkin workspace and install gazebo on your pc

**Comment by sezan92** [comment]
I have Gazebo installed. catkin workspace also available. 
![Error](https://user-images.githubusercontent.com/11025093/61214890-23b21980-a744-11e9-8888-d28e3068a55c.png)

**Comment by yang2lalang** [comment]
Do you have visp installed?

The project has a dependency on visp, used for some matrix-vector operations

Your error suggests you did not install visp

please install visp: https://visp.inria.fr/install/ 

or provide a path to the FindVisp.cmake file to the cmake configuration  panel if visp is installed on your computer

or export the VISP path in your enviroment variables  if visp is installed on your computer
