### ISSUE TITLE
error while installing with log2plot 

### ISSUE THREAD

**Issue by AbhinayNS** [oKermorgant/cdpr#2]
![Screenshot from 2020-09-04 18-45-40](https://user-images.githubusercontent.com/47498924/92243273-dc09c680-eede-11ea-8a33-a668e1238bfe.png)

i looked for log2plot in the internet and found one pkg in git by you, i copied the files into the same workspace and tried building it again but the same error shows up and also the pkg that i found says it is ros-agnostic 
should an older version be used, but i didn't find any older version 
please suggest the solution for this

**Comment by oKermorgant** [comment]
Hi, 

Indeed you need to ensure CMake can find the package.
One easy step is to `sudo make install` this package. 

Also, it should not be put in a ROS workspace but rather in a separate code directory.
