### ISSUE TITLE
Catkin_make error

### ISSUE THREAD

**Issue by siddharthumakarthikeyan** [oKermorgant/cdpr#4]
When I do catkin make I face this error. Can someone guide me how to overcome this.!?
![IMG-20210614-WA0006.jpeg](https://user-images.githubusercontent.com/82173562/121824928-443ad380-cccd-11eb-8a66-d0ccff03a7a3.jpeg)

**Comment by oKermorgant** [comment]
Hi, 
My guess is that you should activate at least C++14 in the CMake file.
I just pushed a small commit that may do the trick.

**Comment by siddharthumakarthikeyan** [comment]
Thanks oKermorgant. I will give a try now.!

**Comment by siddharthumakarthikeyan** [comment]
Thanks oKermorgant. I update both the directory and found a different error now


![Screenshot from 2021-06-14 16-54-56](https://user-images.githubusercontent.com/82173562/121885163-73832c00-cd31-11eb-9e4f-0a3784e3e440.png)

**Comment by yang2lalang** [comment]
Hello, can you check your gcc --version

you may need to update your compiler to be able to use C++ 14

please see:  https://askubuntu.com/questions/1283643/how-to-update-c-or-g-to-version-14-or-above

**Comment by oKermorgant** [comment]
Fine, I did the same correction in the `trajectory_generator` package.

**Comment by oKermorgant** [comment]
> Hello, can you check your gcc --version
> 
> you may need to update your compiler to be able to use C++ 14
> 
> please see: https://askubuntu.com/questions/1283643/how-to-update-c-or-g-to-version-14-or-above

Hi Yuchuan, one issue is that after `find_package` some of the dependencies may set the C++ version to a lower one. So we should set it after all `find_package` calls.

**Comment by siddharthumakarthikeyan** [comment]
Thanks @oKermorgant and @yang2lalang for solving my query. Actually the C++ version error is resolved and left with a small error. I think that might be due to improper installation of visp3. Kindly look at my error and suggest me the step wise installation to overcome that error (If it is visp3, Kindly give a solution how to install that). Thanks a lot 



![Screenshot from 2021-06-14 17-19-12](https://user-images.githubusercontent.com/82173562/121887921-007bb480-cd35-11eb-91ac-7da331a10874.png)

**Comment by siddharthumakarthikeyan** [comment]
It got rectified. Thanks for your support.
